# Generated by Django 5.2.6 on 2026-02-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('organization', '0002_company_description_company_slug_store_address_and_more'),
        ('products', '0002_product_avg_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.store'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
