# Generated by Django 5.2.6 on 2026-02-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_options_alter_inventory_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
