# Generated by Django 5.2.6 on 2026-02-04 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_wishlist_is_primary_wishlist_is_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_user_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max distinct users allowed', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
