# Generated by Django 5.2.6 on 2026-02-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartcoupon'),
        ('products', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='total_user_limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit_per_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_pre_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('cart', 'Cart')], default='cart', max_length=20),
        ),
    ]
