# Generated by Django 5.2.6 on 2026-01-30 08:57

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attachment',
            name='products_at_entity__d7b4b7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('variation', 'Variation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=products.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
