# Generated by Django 5.2.6 on 2026-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
    ]
