# Generated by Django 5.2.6 on 2026-02-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company_description_company_slug_store_address_and_more'),
        ('products', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('brand', 'Brand'), ('variation', 'Variation'), ('review', 'Review')], max_length=50),
        ),
        migrations.AlterField(
            model_name='brand',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='organization.store'),
        ),
    ]
