# Generated by Django 5.2.6 on 2026-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_attachment_entity_type_alter_brand_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
