# Generated by Django 5.2.6 on 2026-02-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_primary',
        ),
    ]
