# Generated by Django 5.2.6 on 2026-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariant_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('category', 'Category'), ('target', 'Target Group'), ('collection', 'Collection')], default='category', max_length=20),
        ),
    ]
