# Generated by Django 5.2.6 on 2026-02-14 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_company_description_company_slug_store_address_and_more'),
        ('products', '0009_remove_product_primary_category_product_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('slug', 'store')},
        ),
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='organization.store')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='products.collectioncategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.targetgroup'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='categories', to='products.targetgroup'),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='category_type',
        ),
    ]
