# Generated by Django 5.2.6 on 2026-02-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_targetgroup_alter_productcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory'),
        ),
        migrations.DeleteModel(
            name='CollectionCategory',
        ),
        migrations.DeleteModel(
            name='TargetGroup',
        ),
    ]
