# Generated by Django 5.2.6 on 2026-02-25 06:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_review_variant_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='lft',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='rght',
            field=models.PositiveIntegerField(default=3, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory'),
        ),
    ]
